/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;

namespace ComputerCraftRemote
{
  public static class servicesConstants
  {
    public static string DEFAULT_POOL_NAME = "Unassigned";
    public static string DEFAULT_OWNER_NAME = "None";
  }
}
