/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ComputerCraftRemote
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class PoolOwnner : TBase
  {
    private string _poolName;
    private string _ownerName;

    public string PoolName
    {
      get
      {
        return _poolName;
      }
      set
      {
        __isset.poolName = true;
        this._poolName = value;
      }
    }

    public string OwnerName
    {
      get
      {
        return _ownerName;
      }
      set
      {
        __isset.ownerName = true;
        this._ownerName = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool poolName;
      public bool ownerName;
    }

    public PoolOwnner() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              PoolName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              OwnerName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("PoolOwnner");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (PoolName != null && __isset.poolName) {
        field.Name = "poolName";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(PoolName);
        oprot.WriteFieldEnd();
      }
      if (OwnerName != null && __isset.ownerName) {
        field.Name = "ownerName";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(OwnerName);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("PoolOwnner(");
      sb.Append("PoolName: ");
      sb.Append(PoolName);
      sb.Append(",OwnerName: ");
      sb.Append(OwnerName);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
