/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ComputerCraftRemote
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TurtleIdPool : TBase
  {
    private int _turtleId;
    private string _poolName;
    private string _startLocation;

    public int TurtleId
    {
      get
      {
        return _turtleId;
      }
      set
      {
        __isset.turtleId = true;
        this._turtleId = value;
      }
    }

    public string PoolName
    {
      get
      {
        return _poolName;
      }
      set
      {
        __isset.poolName = true;
        this._poolName = value;
      }
    }

    public string StartLocation
    {
      get
      {
        return _startLocation;
      }
      set
      {
        __isset.startLocation = true;
        this._startLocation = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool turtleId;
      public bool poolName;
      public bool startLocation;
    }

    public TurtleIdPool() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              TurtleId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              PoolName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              StartLocation = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("TurtleIdPool");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.turtleId) {
        field.Name = "turtleId";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(TurtleId);
        oprot.WriteFieldEnd();
      }
      if (PoolName != null && __isset.poolName) {
        field.Name = "poolName";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(PoolName);
        oprot.WriteFieldEnd();
      }
      if (StartLocation != null && __isset.startLocation) {
        field.Name = "startLocation";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(StartLocation);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("TurtleIdPool(");
      sb.Append("TurtleId: ");
      sb.Append(TurtleId);
      sb.Append(",PoolName: ");
      sb.Append(PoolName);
      sb.Append(",StartLocation: ");
      sb.Append(StartLocation);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
