/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ComputerCraftRemote
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Work : TBase
  {
    private int _computerID;
    private string _command;

    public int ComputerID
    {
      get
      {
        return _computerID;
      }
      set
      {
        __isset.computerID = true;
        this._computerID = value;
      }
    }

    public string Command
    {
      get
      {
        return _command;
      }
      set
      {
        __isset.command = true;
        this._command = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool computerID;
      public bool command;
    }

    public Work() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              ComputerID = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              Command = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Work");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.computerID) {
        field.Name = "computerID";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ComputerID);
        oprot.WriteFieldEnd();
      }
      if (Command != null && __isset.command) {
        field.Name = "command";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Command);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Work(");
      sb.Append("ComputerID: ");
      sb.Append(ComputerID);
      sb.Append(",Command: ");
      sb.Append(Command);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
